### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by wedgiebee** [hydescarf/Obsidian-Theme-Mado-Miniflow#1]
This is such an awesome theme! I turned off the waves just because I like the simplicity without, and I love how the note pane feels like a little page of paper!

Are there any plans to support this theme on mobile?

**Comment by hydescarf** [comment]
Thank you!
I have plans to support mobile now. However, as I don't use mobile app at all, would be nice if you can let me know what issues you are facing with it. Additionally, what kind of styles would you expect to see on the mobile app from this theme?

The current issues I'm aware of are:
- hidden buttons for the sidebar
- thinner main pane/note due to margin used on it

**Comment by wedgiebee** [comment]
Awesome! Yeah those are 2 issues I've seen so far, here are some other points of feedback as well. Hope it helps! :)

# Note View
![IMG_4282](https://user-images.githubusercontent.com/3342937/183137075-82bc3aef-ab37-4ae3-9412-71921dad7444.PNG)
- Only one character of the note title is visible (the full note title is much longer)
- The black background doesn't stretch to the top/bottom of the phone

# File Explorer View
![IMG_4281](https://user-images.githubusercontent.com/3342937/183137255-2dc9083e-5c5d-461e-9671-3b2c40cfe079.PNG)
- Like with note view, the file explorer view doesn't stretch all the way to the bottom (it seems to stretch to the top but almost a little too far where the text almost gets cut off? You can see how it overlaps with the phone system info at the top)
- Different themes handle it differently, but on mobile I prefer it when the file explorer view takes up the whole screen horizontally, rather than leaving the unused black space at the right. That's just preference!

**Comment by hydescarf** [comment]
Most of them should be fixed in the live update now! https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/commit/fb013389f0585408ce22c65bdff929f2530ac8d1

Although, I still notice a bottom part gap issue on my side, might need to explore other theme's solution to this.
I have also added in some spacing during Reading Mode, not sure if it's a good choice, do let me know about it if possible.
Let me know anything else if you encountered any.

**Comment by wedgiebee** [comment]
This is awesome thank you so much! Yeah everything looks great, just that bottom gap you mentioned. Thanks for the fix, I'll let you know if I encounter anything else :)

**Comment by hydescarf** [comment]
On live update of https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/commit/41d72bd5260294bcd3bf0744e66246bcb5fa72ee , all issues should now be solved.
Aside from the sidebar bottom-spacing fix, I also shrunk a little on the size of the icons beside the Note Title.

That should be all for now, I'll close the thread, but feel free to reopen them if there is something I missed.
