### ISSUE TITLE
Theme Color from Style Settings not applied

### ISSUE THREAD

**Issue by Cutuchiqueno** [hydescarf/Obsidian-Theme-Mado-Miniflow#30]
I do not know if I misunderstand something or something really does not work with my installation, but I have the following problem:

What ever I change in `Style Settings -> Madow Miniflow -> Theme Section -> Theme Color`  (`Daisy Blue`, `Red Sky`, ...), it has no effect on any clolor in my Obsidian.

Expected: The color of some elements like the wave pattern or accent color or alike would change (See screenshot below, which has `Greeny` applied, but looks the same as with every other value)

On the other hand, if I change the accent color in Obsidian `Settings -> Appearance` some elements like those mentioned before change (not the background color however).

Is this a bug, or do I get something wrong?

![grafik](https://user-images.githubusercontent.com/306064/227737015-22483d3a-0979-49ee-a3eb-ea8e24f8860e.png)

**Comment by hydescarf** [comment]
I'm not sure if I'm replicating your issue in the same way, but here's what my take.

The theme color in `Settings > Appearance` has to be reset to default with the reset button beside it. I assume it is because it has the highest priority over other settings, thus the theme color in Style Settings will never work if a color is applied in the Settings, unless I'm wrong.

On a side note, the background color (which has a shade of blue) doesn't react to the theme color as they aren't manipulative in Mado theme, except the wave color though.

Let me know the result!

**Comment by Cutuchiqueno** [comment]
Thx for the explanation. You were right 👍. After doing a reset on the accent colour in Settings -> Appearance the Mado Minimal colours are applied correctly.
