### ISSUE TITLE
Option to customize background colour

### ISSUE THREAD

**Issue by amzon-ex** [hydescarf/Obsidian-Theme-Mado-Miniflow#34]
Hi, I have been using your theme for some time and I appreciate how beautiful it is, especially with all these options to customize the look to your liking. I use this in conjunction with the Style Settings plugin.

I would also love to see an option to customize the background colour, to switch from this default of gunmetal shades.

**Comment by hydescarf** [comment]
I've add the option to the Style Settings now.
However, the background colour is actually fine-tuned manually, and some of the elements are heavily dependent on it. In other words, they are hard-coded :(
Just take note that changing the colours might make some of the elements indistinguishable. 

I'm not actively maintaining this to be honest, so that's all I can do for now.

**Comment by amzon-ex** [comment]
Okay, I'll try this out and look out for possible artifacts that arise due to hard-coding. Thanks for the hotfix - how do I use it? I don't see a release.

**Comment by hydescarf** [comment]
I forgot to write a release, woops!
The update is already live, you can fetch them now in Obsidian. It's the same way as changing the accent colours with Light & Dark mode option.
