### ISSUE TITLE
Canvas text is blurry when the Canvas is focused

### ISSUE THREAD

**Issue by reiyuguigui** [hydescarf/Obsidian-Theme-Mado-Miniflow#36]
Hey, great work! Mado Miniflow is wonderfully minimalist and looks great. Without a doubt my favorite theme, but I've been struggling with using a CANVAS with this theme.

When I use Canvas mode, some of my text is notably blurry in Mado Miniflow--when I change themes, the text is no longer blurry. The strangest part of all this is that the text blurriness only happens when Obsidian is focused. If I am on a different monitor or alt tabbed, the blurriness goes away.

When I was searching for ways to fix it, I found [someone who had the exact issue and recommended some custom CSS to fix the issue](https://forum.obsidian.md/t/canvas-text-is-slightly-blurry-due-to-non-integer-pixel-offsets/56436/3). I used the custom CSS but it didn't do anything for me.

This is my first time submitting an "issue," please do let me know if there are any files I can provide to help you troubleshoot.

Thank you for your time!

**Comment by hydescarf** [comment]
Thanks for the detailed report!
Looking at the post's solution, I suspect it has something to do with `transform` and went and look for the obsidian original CSS file for it, and it is!
Though, that won't make sense if the default theme has no issue with it, so I went and scrap my codes one part by one and found the culprit!

The mentioned code however, consists of just these elements that don't directly affect the text. 
```
.markdown-embed{
	border:var(--border);
	border-radius:var(--button-radius);
	padding:var(--embed-padding);
}
```
I assume the padding and border size affected the font size, which Obsidian probably pre-calculated the perfect font size for zooming that doesn't account for custom theme? (E.g., Turning the font size into 16.01px instead of 16px?) Just a wild guess.


Anyway, the fix (which can be used as a custom CSS) is:
```
.is-focused .canvas-node-content.markdown-embed > .markdown-embed-content > .markdown-preview-view {
	transform: unset;
}
```
That worked for me, but let me know if it doesn't work on your side though (or if you encountered side effects from it).

**Comment by reiyuguigui** [comment]
Works perfectly!!
Thank you so much for your work on the theme and for fixing this so quickly!! You're a real one!!

**Comment by hydescarf** [comment]
A little further investigating, `border-radius` was the culprit behind, but not sure how honestly lol.
Anyway, the theme is now updated to fix the blurry text issue.

The custom CSS fix above should be usable on other themes as well, so you can keep that if you need in the future.
