### ISSUE TITLE
Opening Canvas Embedded PDFs in New Tab Fails

### ISSUE THREAD

**Issue by andywhitaker** [hydescarf/Obsidian-Theme-Mado-Miniflow#41]
First I want to say I love this theme. By far my favorite and I've looked at SO many! Thanks for the hard work!

I am running into an odd issue that seems to be only a problem when using this theme though.. when I embed a PDF into a canvas then CMD+click on the title of that PDF  on the canvas to open it in a new tab rather than the same tab I'm in, it opens a new blank tab. I only see this problem when using this theme.

No the end of the world but if it's fixable and you were interested I figured I'd report it.

Thanks!

**Comment by hydescarf** [comment]
Thank for the report!
It seems like the PDF reader has some code that was trying to refer to the new-tab info, which the theme also use it for an animation. The reader, failing to obtain the info possibly caused by the animation, returns blank page to the tab.

Not sure what's the real fix, but I've made an bandage fix update to disable the animation on PDF tabs.
Let me know if it didn't work.

**Comment by andywhitaker** [comment]
That 100% worked and you also blew my mind how fast you responded to and fixed this! Appreciate it very much! Thanks for sharing the theme and for taking the time to respond to and fix this!
