### ISSUE TITLE
[Bug] Dotpoints In Transcluded Notes

### ISSUE THREAD

**Issue by 8veStory** [hydescarf/Obsidian-Theme-Mado-Miniflow#7]
Hello! I'm really loving the theme, it's so beautifully designed 🥺! However, I noticed that dotpoints in transcluded notes may be styled weirdly.

Here's what I mean:
![image](https://user-images.githubusercontent.com/29248979/184118443-084517d7-f53d-478a-98bc-3d10b5de78ae.png)
![image](https://user-images.githubusercontent.com/29248979/184118500-8292e0a8-0ddf-45b2-ae7a-7dab3b20d2c9.png)

**System Information**
- OS: Tested on Fedora 36 and Debian 11
- Obsidian Version: 0.15.9

**Comment by hydescarf** [comment]
Issue is hopefully fixed in the latest update https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/commit/d7746671473e8c10908bd09cd6888a5d307c360c !
I think it was actually fixed in the previous update, either way I give it a new style for the dot in this update so that it fits to the height of the text.

For Mado 11, I'll backport them in the future in my free time.

Closing issue but feel free to reopen it if it didn't work on your side!
