### ISSUE TITLE
[Feature Request] Style Settings integration

### ISSUE THREAD

**Issue by ryadaj** [hydescarf/Obsidian-Theme-Mado-Miniflow#8]
Thanks for an absolutely brilliant theme.

For us non-CSS savvy folks, it'd be handy to be able to adjust basic features using Style Settings, such as showing or hiding buttons, changing text colours, and changing the accent colours.

Whether the upcoming default theme will affect this somehow, I'm not sure.

**Comment by hydescarf** [comment]
Yeah, support for Style Settings is in the roadmap now, but won't be in the near future as I have little time to develop.

On the other hand, I just learned about the new default theme, I think it'll tank the theme if a lot of changes are introduced since it uses some of the default styles, which I should focus on that first if that's the case.

**Comment by ryadaj** [comment]
Makes perfect sense to wait! 

Thanks again for such a phenomenal and enjoyable theme.

**Comment by hydescarf** [comment]
The theme has updated to v1.0.0, and is now supporting Style Settings!
Thank you for your wait!
